-- This file was generated by setup script
-- Generated at: 2024-11-25 13:24:55

-- airline.lua
return {
	 "vim-airline/vim-airline",
  dependencies = {
    "vim-airline/vim-airline-themes",
  },
  config = function()
    vim.cmd([[
      if !exists('g:airline_symbols')
        let g:airline_symbols = {}
      endif
    ]])
    vim.cmd('let g:airline#themes#nord#palette = {}')
    vim.g['airline#extensions#tabline#enabled'] = 1
    vim.g['airline_powerline_fonts'] = 1
    vim.g['airline_theme'] = 'dark'
  end,
}
