-- This file was generated by setup script
-- Generated at: 2024-11-25 13:24:55

-- coc.lua
return {
"neoclide/coc.nvim",
  branch = "release",
  config = function()
    vim.opt.updatetime = 300
    vim.opt.signcolumn = "yes"
    
    local keyset = vim.keymap.set
    function _G.check_back_space()
      local col = vim.fn.col('.') - 1
      return col == 0 or vim.fn.getline('.'):sub(col, col):match('%s')
    end
    
    local opts = {silent = true, noremap = true, expr = true}
    keyset("i", "<TAB>", 'coc#pum#visible() ? coc#pum#next(1) : v:lua.check_back_space() ? "<TAB>" : coc#refresh()', opts)
    keyset("i", "<S-TAB>", [[coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"]], opts)
    keyset("i", "<cr>", [[coc#pum#visible() ? coc#pum#confirm() : "\<CR>"]], opts)
    
    keyset("n", "<S-A-f>", "<cmd>call CocAction('format')<CR>", {
      silent = true,
      noremap = true,
      desc = "Format document with coc-format"
    })
    
    keyset("v", "<S-A-f>", "<cmd>call CocAction('formatSelected')<CR>", {
      silent = true,
      noremap = true,
      desc = "Format selected code with coc-format"
    })
  end,
}
