-- This file was generated by setup script
-- Generated at: 2024-11-25 13:24:55

-- nord.lua
return {
	 "shaunsingh/nord.nvim",
  lazy = false,
  priority = 1000,
  config = function()
    vim.cmd([[colorscheme nord]])
  end,
}
