-- This file was generated by setup script
-- Generated at: 2024-11-25 13:24:55

-- rustaceanvim.lua
return {
	 'mrcjkb/rustaceanvim',
  version = '^5',
  ft = { 'rust' },
  lazy = false,
  config = function()
    vim.g.rustaceanvim = {
      server = {
        on_attach = function(client, bufnr)
        end,
        settings = {
          ['rust-analyzer'] = {
            checkOnSave = {
              command = "clippy",
            },
          },
        },
      },
    }
  end,
}
