-- This file was generated by setup script
-- Generated at: 2024-11-25 13:24:55

-- yanky.lua
return {
 "gbprod/yanky.nvim",
  config = function()
    require("yanky").setup({
      highlight = {
        timer = 200,
      },
      preserve_cursor_position = {
        enabled = true
      }
    })
    vim.keymap.set('n', 'p', "<Plug>(YankyPutAfter)")
    vim.keymap.set('n', 'P', "<Plug>(YankyPutBefore)")
    vim.keymap.set('n', '<c-y>', ":YankyRingHistory<cr>")
  end,
}
