-- This file was generated by setup script
-- Generated at: 2024-11-25 13:24:55

-- keymaps.lua
local keymap = vim.keymap.set
local opts = { noremap = true, silent = true }

-- リーダーキー
vim.g.mapleader = " "

-- ターミナル関連
keymap('n', '<C-t>x', ':split | terminal<CR>', opts)
keymap('n', '<C-t>', ':terminal<CR>', opts)
keymap('t', '<ESC>', '<C-\\><C-n>', opts)

-- vimをまとめて終了する
vim.api.nvim_set_keymap('n', '<leader>q', ':qa<CR>', {noremap = true, silent = true})

-- バッファ操作
keymap('n', '<C-l>', ':bnext<CR>', opts)
keymap('n', '<C-h>', ':bprevious<CR>', opts)
keymap('n', '<C-d>', ':bdelete<CR>', opts)

-- F5でPython実行
keymap('n', '<F5>', require('core.functions').run_python, opts)
keymap('i', '<F5>', function()
    vim.cmd('stopinsert')
    require('core.functions').run_python()
end, opts)
