-- This file was generated by setup script
-- Generated at: 2024-11-25 13:24:55

-- options.lua
local opt = vim.opt

-- エンコーディング
opt.encoding = 'utf-8'
opt.fileencoding = 'utf-8'

-- 表示
opt.number = true
opt.title = true
opt.scrolloff = 8
opt.scrolljump = 5
opt.ttyfast = true

-- インデント
opt.autoindent = true
opt.smartindent = true
opt.expandtab = true
opt.tabstop = 2
opt.shiftwidth = 2

-- 検索
opt.hlsearch = true

-- システム
opt.undofile = true
opt.undodir = vim.fn.expand('~/.config/nvim/undo')
opt.mouse = ''
opt.clipboard:append({"unnamedplus"})
opt.lazyredraw = true
opt.ttyfast = true
